import { defaultBackgroundMedia, defaultTheme, type ThemeConfig } from "@/lib/theme";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  mood: string;
  theme: ThemeConfig;
}

interface PresetDefinition {
  id: string;
  name: string;
  description: string;
  mood: string;
  primary: string;
  primaryGlow: string;
  background: string;
  backgroundSecondary: string;
  card: string;
  foreground: string;
  muted: string;
  border: string;
  gradientTo: string;
  cardGradientTo: string;
  fontFamily: string;
  cardRadius: number;
  cardSpacing: number;
  glowIntensity: number;
  blurIntensity: number;
  maxWidth?: string;
}

const createPreset = (definition: PresetDefinition): ThemePreset => ({
  id: definition.id,
  name: definition.name,
  description: definition.description,
  mood: definition.mood,
  theme: {
    ...defaultTheme,
    primary: definition.primary,
    primaryGlow: definition.primaryGlow,
    background: definition.background,
    backgroundSecondary: definition.backgroundSecondary,
    card: definition.card,
    foreground: definition.foreground,
    muted: definition.muted,
    accent: definition.primary,
    border: definition.border,
    backgroundGradient: {
      from: definition.background,
      to: definition.gradientTo,
      direction: "145deg",
    },
    cardGradient: {
      from: definition.card,
      to: definition.cardGradientTo,
      direction: "135deg",
    },
    profileCard: {
      background: definition.card,
      backgroundSecondary: definition.cardGradientTo,
      foreground: definition.foreground,
      muted: definition.muted,
      border: definition.border,
      accent: definition.primary,
      direction: "135deg",
    },
    contentCard: {
      background: definition.card,
      backgroundSecondary: definition.cardGradientTo,
      foreground: definition.foreground,
      muted: definition.muted,
      border: definition.border,
      accent: definition.primary,
      accentForeground: definition.background,
      direction: "135deg",
    },
    fontFamily: definition.fontFamily,
    cardRadius: definition.cardRadius,
    cardSpacing: definition.cardSpacing,
    maxWidth: definition.maxWidth || "28rem",
    glowIntensity: definition.glowIntensity,
    blurIntensity: definition.blurIntensity,
    backgroundMedia: {
      ...defaultBackgroundMedia,
      type: "gradient",
      overlayColor: definition.background,
    },
  },
});

export const themePresets: ThemePreset[] = [
  createPreset({
    id: "midnight-signal",
    name: "Midnight Signal",
    description: "Deep navy, crisp blue actions and luminous glass cards.",
    mood: "Digital / confident",
    primary: "#4f8cff",
    primaryGlow: "#78b7ff",
    background: "#07111f",
    backgroundSecondary: "#101e31",
    card: "#14253b",
    foreground: "#edf5ff",
    muted: "#9db0c8",
    border: "#29415f",
    gradientTo: "#11284a",
    cardGradientTo: "#1a3150",
    fontFamily: "Poppins, system-ui, sans-serif",
    cardRadius: 18,
    cardSpacing: 14,
    glowIntensity: 0.42,
    blurIntensity: 24,
  }),
  createPreset({
    id: "paper-ink",
    name: "Paper & Ink",
    description: "Warm paper, editorial type and sharp understated cards.",
    mood: "Editorial / timeless",
    primary: "#b44b2a",
    primaryGlow: "#d47751",
    background: "#f3ede2",
    backgroundSecondary: "#e8dfd0",
    card: "#fffaf0",
    foreground: "#28231e",
    muted: "#756b60",
    border: "#d3c5b2",
    gradientTo: "#e4d7c5",
    cardGradientTo: "#f6ecdc",
    fontFamily: "Georgia, serif",
    cardRadius: 6,
    cardSpacing: 16,
    glowIntensity: 0.08,
    blurIntensity: 10,
    maxWidth: "32rem",
  }),
  createPreset({
    id: "terracotta-studio",
    name: "Terracotta Studio",
    description: "Clay neutrals and sun-baked orange for a crafted presence.",
    mood: "Warm / human",
    primary: "#d55f3e",
    primaryGlow: "#ef9870",
    background: "#2c1e19",
    backgroundSecondary: "#453029",
    card: "#52372e",
    foreground: "#fff2e7",
    muted: "#d8b8a6",
    border: "#714b3d",
    gradientTo: "#61382a",
    cardGradientTo: "#674237",
    fontFamily: "Lato, system-ui, sans-serif",
    cardRadius: 22,
    cardSpacing: 12,
    glowIntensity: 0.28,
    blurIntensity: 18,
  }),
  createPreset({
    id: "nordic-moss",
    name: "Nordic Moss",
    description: "Forest greens, misty neutrals and calm organic spacing.",
    mood: "Natural / calm",
    primary: "#6e9b72",
    primaryGlow: "#a2c59d",
    background: "#17211b",
    backgroundSecondary: "#243128",
    card: "#2a392e",
    foreground: "#edf3e9",
    muted: "#aab9a7",
    border: "#415346",
    gradientTo: "#2e4032",
    cardGradientTo: "#344638",
    fontFamily: "Montserrat, system-ui, sans-serif",
    cardRadius: 14,
    cardSpacing: 18,
    glowIntensity: 0.18,
    blurIntensity: 20,
  }),
  createPreset({
    id: "coral-hour",
    name: "Coral Hour",
    description: "Optimistic coral with peach light and soft rounded surfaces.",
    mood: "Social / energetic",
    primary: "#e94f58",
    primaryGlow: "#ff9077",
    background: "#fff1e8",
    backgroundSecondary: "#f9d8ca",
    card: "#fff9f3",
    foreground: "#3c2022",
    muted: "#91676a",
    border: "#edb8aa",
    gradientTo: "#ffc5b0",
    cardGradientTo: "#ffe6da",
    fontFamily: "Poppins, system-ui, sans-serif",
    cardRadius: 24,
    cardSpacing: 12,
    glowIntensity: 0.2,
    blurIntensity: 18,
  }),
  createPreset({
    id: "acid-editorial",
    name: "Acid Editorial",
    description: "Charcoal structure with a sharp lime signal and compact rhythm.",
    mood: "Bold / contemporary",
    primary: "#c7f43d",
    primaryGlow: "#e0ff79",
    background: "#161814",
    backgroundSecondary: "#232620",
    card: "#292d25",
    foreground: "#f4f7eb",
    muted: "#afb7a3",
    border: "#444a3d",
    gradientTo: "#292f1c",
    cardGradientTo: "#343a2c",
    fontFamily: "Montserrat, system-ui, sans-serif",
    cardRadius: 4,
    cardSpacing: 9,
    glowIntensity: 0.16,
    blurIntensity: 8,
    maxWidth: "32rem",
  }),
  createPreset({
    id: "coastal-glass",
    name: "Coastal Glass",
    description: "Sea-glass blues and airy translucent surfaces with gentle depth.",
    mood: "Fresh / open",
    primary: "#167d91",
    primaryGlow: "#5fc3cb",
    background: "#dff1ef",
    backgroundSecondary: "#c3e2df",
    card: "#f2fbf9",
    foreground: "#173a40",
    muted: "#55777b",
    border: "#9ccbc7",
    gradientTo: "#a9d8dc",
    cardGradientTo: "#d9f2ef",
    fontFamily: "Lato, system-ui, sans-serif",
    cardRadius: 20,
    cardSpacing: 15,
    glowIntensity: 0.24,
    blurIntensity: 32,
  }),
  createPreset({
    id: "cherry-noir",
    name: "Cherry Noir",
    description: "Near-black burgundy with restrained cherry highlights.",
    mood: "Dramatic / premium",
    primary: "#e44863",
    primaryGlow: "#ff7b8e",
    background: "#150b10",
    backgroundSecondary: "#28141d",
    card: "#321923",
    foreground: "#fff0f3",
    muted: "#c19aa6",
    border: "#563040",
    gradientTo: "#3f1726",
    cardGradientTo: "#43212d",
    fontFamily: "Playfair Display, Georgia, serif",
    cardRadius: 12,
    cardSpacing: 17,
    glowIntensity: 0.3,
    blurIntensity: 20,
  }),
  createPreset({
    id: "sandstone",
    name: "Sandstone",
    description: "Quiet mineral tones with olive accents and generous breathing room.",
    mood: "Refined / grounded",
    primary: "#6f7744",
    primaryGlow: "#9ca467",
    background: "#e9e0cf",
    backgroundSecondary: "#d9cdb8",
    card: "#f5eddf",
    foreground: "#37352b",
    muted: "#75705f",
    border: "#c7b99f",
    gradientTo: "#cfc1a8",
    cardGradientTo: "#e6dac6",
    fontFamily: "Georgia, serif",
    cardRadius: 10,
    cardSpacing: 20,
    glowIntensity: 0.05,
    blurIntensity: 12,
    maxWidth: "32rem",
  }),
  createPreset({
    id: "cobalt-poster",
    name: "Cobalt Poster",
    description: "Graphic cobalt, red accents and squared poster-like cards.",
    mood: "Graphic / direct",
    primary: "#f04b36",
    primaryGlow: "#ff846f",
    background: "#163d9f",
    backgroundSecondary: "#2450b9",
    card: "#244aa8",
    foreground: "#fff8e8",
    muted: "#c9d5fa",
    border: "#7892df",
    gradientTo: "#0c2b78",
    cardGradientTo: "#183b92",
    fontFamily: "Montserrat, system-ui, sans-serif",
    cardRadius: 2,
    cardSpacing: 10,
    glowIntensity: 0.12,
    blurIntensity: 6,
    maxWidth: "32rem",
  }),
  createPreset({
    id: "soft-lilac",
    name: "Soft Lilac",
    description: "A restrained lilac wash with dark plum type and soft cards.",
    mood: "Gentle / creative",
    primary: "#76529d",
    primaryGlow: "#a77bc5",
    background: "#eee7f0",
    backgroundSecondary: "#ded1e3",
    card: "#faf5fb",
    foreground: "#33253a",
    muted: "#76657d",
    border: "#cbb9d1",
    gradientTo: "#d7c4df",
    cardGradientTo: "#eee2f1",
    fontFamily: "Poppins, system-ui, sans-serif",
    cardRadius: 18,
    cardSpacing: 14,
    glowIntensity: 0.16,
    blurIntensity: 22,
  }),
  createPreset({
    id: "mono-redline",
    name: "Mono Redline",
    description: "Clean monochrome surfaces with one decisive red action color.",
    mood: "Minimal / precise",
    primary: "#d83232",
    primaryGlow: "#f06455",
    background: "#ececea",
    backgroundSecondary: "#dcdcd8",
    card: "#f8f8f4",
    foreground: "#20201e",
    muted: "#686864",
    border: "#c5c5bf",
    gradientTo: "#d3d3ce",
    cardGradientTo: "#eeeeea",
    fontFamily: "Lato, system-ui, sans-serif",
    cardRadius: 8,
    cardSpacing: 12,
    glowIntensity: 0.04,
    blurIntensity: 8,
    maxWidth: "28rem",
  }),
];
